name: sprint start (manual)

on:
  workflow_dispatch:
    inputs:

jobs:
  generate_burndown_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate burndown chart
        uses: szenius/notion-burndown@2.0.4
        with:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DB_BACKLOG: ${{ secrets.DATABASE_ID_BACKLOG }}
          NOTION_DB_SPRINT_SUMMARY: ${{ secrets.DATABASE_ID_SPRINT_SUMMARY }}
          NOTION_DB_DAILY_SUMMARY: ${{ secrets.DATABASE_ID_DAILY_SUMMARY }}
          NOTION_PROPERTY_SPRINT: Sprint
          NOTION_PROPERTY_ESTIMATE: Story Estimate
          NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: "*Ready to Deploy*|*DONE*"
          SPRINT_START: true
      - name: Commit burndown chart
        continue-on-error: true # not every run is at sprint start, so there may not be a chart
        run: |
          git config --local user.email ${{ secrets.GH_USER_EMAIL }}
          git config --local user.name "supplyally-bot"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        continue-on-error: true # not every run is at sprint start, so there may not be a chart
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_SUPPLYALLY_BOT }}
          force: true
      - name: On failure, send Slack message
        uses: craftech-io/slack-action@v1
        if: failure()
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_SALLY_DEV }}
          status: failure
